---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Executing 'benthos --version'
      ansible.builtin.command: benthos --version
      changed_when: false
      register: "benthos_test_output"
    - name: Output from 'benthos --version'
      ansible.builtin.debug:
        msg: "{{ benthos_test_output.stdout }}"
